AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  AlarmSNSTopicName:
    Type: String
    Description: 'Topic alarm'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'
Resources:

  # KMS AWS managed key for SSE pn-apiKey DynamoDB table
  UserAttributesTableEncryptKey:
    Type: 'AWS::KMS::Key'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: Symmetric default key to encrypt table
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  UserAttributesTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain 
    Properties:
      TableName: !Sub '${ProjectName}-UserAttributes'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "S"
        - AttributeName: "requestId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "requestId-gsi"
          KeySchema:
            - AttributeName: "requestId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification: 
        StreamViewType: NEW_IMAGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        KMSMasterKeyId: !Ref ApiKeyTablesEncryptKeyId
        SSEEnabled: true
        SSEType: KMS
          
  UserAttributesActionsQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain 
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-user-attributes-actions'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName 
        DelaySeconds: 1

  PnUserAttributesLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain 
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-user-attributes'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn

Outputs:

  # Actions Queue parameters
  UserAttributesActionsQueueName:
    Value: !GetAtt UserAttributesActionsQueue.Outputs.QueueName
    Description: pn-user-attributes-actions input queue name
  UserAttributesActionsQueueURL:
    Value: !GetAtt UserAttributesActionsQueue.Outputs.QueueURL
    Description: pn-user-attributes-actions input queue URL
  UserAttributesActionsQueueARN:
    Value: !GetAtt UserAttributesActionsQueue.Outputs.QueueARN
    Description: pn-user-attributes-actions input queue ARN
  UserAttributesActionsQueueAlarmARN:
    Value: !GetAtt UserAttributesActionsQueue.Outputs.SqsDLQAlarmArn
    Description: pn-user-attributes-actions input queue alarm ARN
  UserAttributesActionsQueueAgeAlarmARN:
    Value: !GetAtt UserAttributesActionsQueue.Outputs.SqsAgeAlarmArn
    Description: pn-user-attributes-actions input queue alarm ARN

  # Table parameters
  UserAttributesTableName:
    Description: Dynamo Name used by application to access the key-value store
    Value: !Ref UserAttributesTable
  UserAttributesTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store
    Value: !Sub '${UserAttributesTable.Arn}'

  # Log group exports
  EcsLogGroup:
    Value: !GetAtt PnUserAttributesLogGroup.Outputs.LogGroupName